name: Deploy Static Site to Azure Static Web App

on:
  push:
    branches:
      - main  # o la rama que desees

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Desplegar a Azure Static Web App
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_STONE_005B92903 }}
          action: "upload"  # Esta acción indica que estamos subiendo la aplicación

          # Configuración de las rutas de la aplicación (ajusta si es necesario)
          app_location: "/"  # Ruta donde se encuentran tus archivos HTML, CSS, etc.
          api_location: ""   # Deja vacío si no usas una API
          output_location: "/"  # Si no hay un directorio de salida, apunta a la raíz

          github_id_token: ${{ steps.idtoken.outputs.result }}  # Mantén esta autenticación si la estás usando
