name: Deploy Static Site to Azure Static Web App

on:
  push:
    branches:
      - main  # o la rama que desees
  pull_request:
    types:
      - closed  # Este evento activar치 el job cuando un PR se cierre

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del c칩digo
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Desplegar a Azure Static Web App
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_STONE_005B92903 }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "/"

  close-pull-request-job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'  # Solo ejecuta esto cuando se cierre un PR
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request Deployment
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"  # Esta acci칩n cierra la implementaci칩n asociada al PR
