name: Deploy Static Site to Azure Static Web App

on:
  push:
    branches:
      - main  # o la rama que desees
  pull_request:
    types:
      - closed  # Este evento activará el job cuando un PR se cierre

jobs:
  # Job de construcción y despliegue
  build-and-deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    permissions:
      id-token: write  # Necesario para generar el token de autenticación
      contents: read  # Acceso al contenido del repositorio

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Desplegar a Azure Static Web App
      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_STONE_005B92903 }}  # Token de Azure
          action: "upload"  # Acción de despliegue
          app_location: "/"  # Ubicación de la aplicación (en tu caso, todo está en la raíz, incluyendo el index.html)
          api_location: ""  # No se necesita una API
          output_location: "/"  # Ubicación de los archivos a desplegar, en este caso la raíz

  # Job para cerrar la implementación de un Pull Request
  close-pull-request-job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'  # Solo ejecuta esto cuando se cierre un PR
    runs-on: ubuntu-latest
    name: Close Pull Request Job

    steps:
      - name: Close Pull Request Deployment
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"  # Esta acción cierra la implementación asociada al PR

